### ISSUE TITLE
Missing 404 page

### ISSUE THREAD

**Issue by brezzhnev** [kyrylo/kyrylo.org#3]
Hi, when I walked on your site, I was faced with the fact that when I enter a non-existent page in URL, I see    blank page (with layout) and page title "All [page URI]". This is a significant bug, please fix it!

**Comment by vladsypchenko** [comment]
Hi Artem! When I walked on our project site, I was faced with face that when I try to write new post on the news page, I see fully unmarkable page. So I have to add news via SQL-request (SQL-request, Karl!). This is a significant bug, please fix it!

**Comment by brezzhnev** [comment]
@vladsypchenko, oh shit, your project is wonderful! I hope your developers help you create a SQL query :) Finally, how it relates to the issue created by me?

**Comment by vladsypchenko** [comment]
@brezzhnev, the main problem lies in the fact that our team had no previous experience in the post by writing SQL-queries. In this fact, we surprised incompetence of previous work.

It seemed to me that you have to do with it, dawg.

**Comment by brezzhnev** [comment]
@vladsypchenko, I think it is delusion. If the project was written by incompetent, you should improve it, or...examine the debug function. That's all, I see no reason to continue idle chatter.

**Comment by vladsypchenko** [comment]
@brezzhnev, It all hints, allusions.

**Comment by kyrylo** [comment]
Thanks everybody for the feedback ( 😨 )

I don't have it because I don't care enough about it. I will consider having it in the future :P
